// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2018 The go-netbox Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewAPIDcimConsoleConnectionsListParams creates a new APIDcimConsoleConnectionsListParams object
// with the default values initialized.
func NewAPIDcimConsoleConnectionsListParams() *APIDcimConsoleConnectionsListParams {
	var ()
	return &APIDcimConsoleConnectionsListParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewAPIDcimConsoleConnectionsListParamsWithTimeout creates a new APIDcimConsoleConnectionsListParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewAPIDcimConsoleConnectionsListParamsWithTimeout(timeout time.Duration) *APIDcimConsoleConnectionsListParams {
	var ()
	return &APIDcimConsoleConnectionsListParams{

		timeout: timeout,
	}
}

// NewAPIDcimConsoleConnectionsListParamsWithContext creates a new APIDcimConsoleConnectionsListParams object
// with the default values initialized, and the ability to set a context for a request
func NewAPIDcimConsoleConnectionsListParamsWithContext(ctx context.Context) *APIDcimConsoleConnectionsListParams {
	var ()
	return &APIDcimConsoleConnectionsListParams{

		Context: ctx,
	}
}

// NewAPIDcimConsoleConnectionsListParamsWithHTTPClient creates a new APIDcimConsoleConnectionsListParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewAPIDcimConsoleConnectionsListParamsWithHTTPClient(client *http.Client) *APIDcimConsoleConnectionsListParams {
	var ()
	return &APIDcimConsoleConnectionsListParams{
		HTTPClient: client,
	}
}

/*APIDcimConsoleConnectionsListParams contains all the parameters to send to the API endpoint
for the api dcim console connections list operation typically these are written to a http.Request
*/
type APIDcimConsoleConnectionsListParams struct {

	/*ConnectionStatus*/
	ConnectionStatus *string
	/*Device*/
	Device *string
	/*Limit
	  Number of results to return per page.

	*/
	Limit *int64
	/*Name*/
	Name *string
	/*Offset
	  The initial index from which to return the results.

	*/
	Offset *int64
	/*Site*/
	Site *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the api dcim console connections list params
func (o *APIDcimConsoleConnectionsListParams) WithTimeout(timeout time.Duration) *APIDcimConsoleConnectionsListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the api dcim console connections list params
func (o *APIDcimConsoleConnectionsListParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the api dcim console connections list params
func (o *APIDcimConsoleConnectionsListParams) WithContext(ctx context.Context) *APIDcimConsoleConnectionsListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the api dcim console connections list params
func (o *APIDcimConsoleConnectionsListParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the api dcim console connections list params
func (o *APIDcimConsoleConnectionsListParams) WithHTTPClient(client *http.Client) *APIDcimConsoleConnectionsListParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the api dcim console connections list params
func (o *APIDcimConsoleConnectionsListParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithConnectionStatus adds the connectionStatus to the api dcim console connections list params
func (o *APIDcimConsoleConnectionsListParams) WithConnectionStatus(connectionStatus *string) *APIDcimConsoleConnectionsListParams {
	o.SetConnectionStatus(connectionStatus)
	return o
}

// SetConnectionStatus adds the connectionStatus to the api dcim console connections list params
func (o *APIDcimConsoleConnectionsListParams) SetConnectionStatus(connectionStatus *string) {
	o.ConnectionStatus = connectionStatus
}

// WithDevice adds the device to the api dcim console connections list params
func (o *APIDcimConsoleConnectionsListParams) WithDevice(device *string) *APIDcimConsoleConnectionsListParams {
	o.SetDevice(device)
	return o
}

// SetDevice adds the device to the api dcim console connections list params
func (o *APIDcimConsoleConnectionsListParams) SetDevice(device *string) {
	o.Device = device
}

// WithLimit adds the limit to the api dcim console connections list params
func (o *APIDcimConsoleConnectionsListParams) WithLimit(limit *int64) *APIDcimConsoleConnectionsListParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the api dcim console connections list params
func (o *APIDcimConsoleConnectionsListParams) SetLimit(limit *int64) {
	o.Limit = limit
}

// WithName adds the name to the api dcim console connections list params
func (o *APIDcimConsoleConnectionsListParams) WithName(name *string) *APIDcimConsoleConnectionsListParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the api dcim console connections list params
func (o *APIDcimConsoleConnectionsListParams) SetName(name *string) {
	o.Name = name
}

// WithOffset adds the offset to the api dcim console connections list params
func (o *APIDcimConsoleConnectionsListParams) WithOffset(offset *int64) *APIDcimConsoleConnectionsListParams {
	o.SetOffset(offset)
	return o
}

// SetOffset adds the offset to the api dcim console connections list params
func (o *APIDcimConsoleConnectionsListParams) SetOffset(offset *int64) {
	o.Offset = offset
}

// WithSite adds the site to the api dcim console connections list params
func (o *APIDcimConsoleConnectionsListParams) WithSite(site *string) *APIDcimConsoleConnectionsListParams {
	o.SetSite(site)
	return o
}

// SetSite adds the site to the api dcim console connections list params
func (o *APIDcimConsoleConnectionsListParams) SetSite(site *string) {
	o.Site = site
}

// WriteToRequest writes these params to a swagger request
func (o *APIDcimConsoleConnectionsListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.ConnectionStatus != nil {

		// query param connection_status
		var qrConnectionStatus string
		if o.ConnectionStatus != nil {
			qrConnectionStatus = *o.ConnectionStatus
		}
		qConnectionStatus := qrConnectionStatus
		if qConnectionStatus != "" {
			if err := r.SetQueryParam("connection_status", qConnectionStatus); err != nil {
				return err
			}
		}

	}

	if o.Device != nil {

		// query param device
		var qrDevice string
		if o.Device != nil {
			qrDevice = *o.Device
		}
		qDevice := qrDevice
		if qDevice != "" {
			if err := r.SetQueryParam("device", qDevice); err != nil {
				return err
			}
		}

	}

	if o.Limit != nil {

		// query param limit
		var qrLimit int64
		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt64(qrLimit)
		if qLimit != "" {
			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}

	}

	if o.Name != nil {

		// query param name
		var qrName string
		if o.Name != nil {
			qrName = *o.Name
		}
		qName := qrName
		if qName != "" {
			if err := r.SetQueryParam("name", qName); err != nil {
				return err
			}
		}

	}

	if o.Offset != nil {

		// query param offset
		var qrOffset int64
		if o.Offset != nil {
			qrOffset = *o.Offset
		}
		qOffset := swag.FormatInt64(qrOffset)
		if qOffset != "" {
			if err := r.SetQueryParam("offset", qOffset); err != nil {
				return err
			}
		}

	}

	if o.Site != nil {

		// query param site
		var qrSite string
		if o.Site != nil {
			qrSite = *o.Site
		}
		qSite := qrSite
		if qSite != "" {
			if err := r.SetQueryParam("site", qSite); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
