// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2018 The go-netbox Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/digitalocean/go-netbox/netbox/models"
)

// NewAPIVirtualizationClustersPartialUpdateParams creates a new APIVirtualizationClustersPartialUpdateParams object
// with the default values initialized.
func NewAPIVirtualizationClustersPartialUpdateParams() *APIVirtualizationClustersPartialUpdateParams {
	var ()
	return &APIVirtualizationClustersPartialUpdateParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewAPIVirtualizationClustersPartialUpdateParamsWithTimeout creates a new APIVirtualizationClustersPartialUpdateParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewAPIVirtualizationClustersPartialUpdateParamsWithTimeout(timeout time.Duration) *APIVirtualizationClustersPartialUpdateParams {
	var ()
	return &APIVirtualizationClustersPartialUpdateParams{

		timeout: timeout,
	}
}

// NewAPIVirtualizationClustersPartialUpdateParamsWithContext creates a new APIVirtualizationClustersPartialUpdateParams object
// with the default values initialized, and the ability to set a context for a request
func NewAPIVirtualizationClustersPartialUpdateParamsWithContext(ctx context.Context) *APIVirtualizationClustersPartialUpdateParams {
	var ()
	return &APIVirtualizationClustersPartialUpdateParams{

		Context: ctx,
	}
}

// NewAPIVirtualizationClustersPartialUpdateParamsWithHTTPClient creates a new APIVirtualizationClustersPartialUpdateParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewAPIVirtualizationClustersPartialUpdateParamsWithHTTPClient(client *http.Client) *APIVirtualizationClustersPartialUpdateParams {
	var ()
	return &APIVirtualizationClustersPartialUpdateParams{
		HTTPClient: client,
	}
}

/*APIVirtualizationClustersPartialUpdateParams contains all the parameters to send to the API endpoint
for the api virtualization clusters partial update operation typically these are written to a http.Request
*/
type APIVirtualizationClustersPartialUpdateParams struct {

	/*Data*/
	Data *models.WritableCluster
	/*ID
	  A unique integer value identifying this cluster.

	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the api virtualization clusters partial update params
func (o *APIVirtualizationClustersPartialUpdateParams) WithTimeout(timeout time.Duration) *APIVirtualizationClustersPartialUpdateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the api virtualization clusters partial update params
func (o *APIVirtualizationClustersPartialUpdateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the api virtualization clusters partial update params
func (o *APIVirtualizationClustersPartialUpdateParams) WithContext(ctx context.Context) *APIVirtualizationClustersPartialUpdateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the api virtualization clusters partial update params
func (o *APIVirtualizationClustersPartialUpdateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the api virtualization clusters partial update params
func (o *APIVirtualizationClustersPartialUpdateParams) WithHTTPClient(client *http.Client) *APIVirtualizationClustersPartialUpdateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the api virtualization clusters partial update params
func (o *APIVirtualizationClustersPartialUpdateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithData adds the data to the api virtualization clusters partial update params
func (o *APIVirtualizationClustersPartialUpdateParams) WithData(data *models.WritableCluster) *APIVirtualizationClustersPartialUpdateParams {
	o.SetData(data)
	return o
}

// SetData adds the data to the api virtualization clusters partial update params
func (o *APIVirtualizationClustersPartialUpdateParams) SetData(data *models.WritableCluster) {
	o.Data = data
}

// WithID adds the id to the api virtualization clusters partial update params
func (o *APIVirtualizationClustersPartialUpdateParams) WithID(id int64) *APIVirtualizationClustersPartialUpdateParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the api virtualization clusters partial update params
func (o *APIVirtualizationClustersPartialUpdateParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *APIVirtualizationClustersPartialUpdateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Data != nil {
		if err := r.SetBodyParam(o.Data); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
