// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2018 The go-netbox Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewAPIIPAMVrfsListParams creates a new APIIPAMVrfsListParams object
// with the default values initialized.
func NewAPIIPAMVrfsListParams() *APIIPAMVrfsListParams {
	var ()
	return &APIIPAMVrfsListParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewAPIIPAMVrfsListParamsWithTimeout creates a new APIIPAMVrfsListParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewAPIIPAMVrfsListParamsWithTimeout(timeout time.Duration) *APIIPAMVrfsListParams {
	var ()
	return &APIIPAMVrfsListParams{

		timeout: timeout,
	}
}

// NewAPIIPAMVrfsListParamsWithContext creates a new APIIPAMVrfsListParams object
// with the default values initialized, and the ability to set a context for a request
func NewAPIIPAMVrfsListParamsWithContext(ctx context.Context) *APIIPAMVrfsListParams {
	var ()
	return &APIIPAMVrfsListParams{

		Context: ctx,
	}
}

// NewAPIIPAMVrfsListParamsWithHTTPClient creates a new APIIPAMVrfsListParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewAPIIPAMVrfsListParamsWithHTTPClient(client *http.Client) *APIIPAMVrfsListParams {
	var ()
	return &APIIPAMVrfsListParams{
		HTTPClient: client,
	}
}

/*APIIPAMVrfsListParams contains all the parameters to send to the API endpoint
for the api ipam vrfs list operation typically these are written to a http.Request
*/
type APIIPAMVrfsListParams struct {

	/*EnforceUnique*/
	EnforceUnique *string
	/*IDIn
	  Multiple values may be separated by commas.

	*/
	IDIn *string
	/*Limit
	  Number of results to return per page.

	*/
	Limit *int64
	/*Name*/
	Name *string
	/*Offset
	  The initial index from which to return the results.

	*/
	Offset *int64
	/*Q*/
	Q *string
	/*Rd*/
	Rd *string
	/*Tag*/
	Tag *string
	/*Tenant*/
	Tenant *string
	/*TenantID*/
	TenantID *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the api ipam vrfs list params
func (o *APIIPAMVrfsListParams) WithTimeout(timeout time.Duration) *APIIPAMVrfsListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the api ipam vrfs list params
func (o *APIIPAMVrfsListParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the api ipam vrfs list params
func (o *APIIPAMVrfsListParams) WithContext(ctx context.Context) *APIIPAMVrfsListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the api ipam vrfs list params
func (o *APIIPAMVrfsListParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the api ipam vrfs list params
func (o *APIIPAMVrfsListParams) WithHTTPClient(client *http.Client) *APIIPAMVrfsListParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the api ipam vrfs list params
func (o *APIIPAMVrfsListParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithEnforceUnique adds the enforceUnique to the api ipam vrfs list params
func (o *APIIPAMVrfsListParams) WithEnforceUnique(enforceUnique *string) *APIIPAMVrfsListParams {
	o.SetEnforceUnique(enforceUnique)
	return o
}

// SetEnforceUnique adds the enforceUnique to the api ipam vrfs list params
func (o *APIIPAMVrfsListParams) SetEnforceUnique(enforceUnique *string) {
	o.EnforceUnique = enforceUnique
}

// WithIDIn adds the iDIn to the api ipam vrfs list params
func (o *APIIPAMVrfsListParams) WithIDIn(iDIn *string) *APIIPAMVrfsListParams {
	o.SetIDIn(iDIn)
	return o
}

// SetIDIn adds the idIn to the api ipam vrfs list params
func (o *APIIPAMVrfsListParams) SetIDIn(iDIn *string) {
	o.IDIn = iDIn
}

// WithLimit adds the limit to the api ipam vrfs list params
func (o *APIIPAMVrfsListParams) WithLimit(limit *int64) *APIIPAMVrfsListParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the api ipam vrfs list params
func (o *APIIPAMVrfsListParams) SetLimit(limit *int64) {
	o.Limit = limit
}

// WithName adds the name to the api ipam vrfs list params
func (o *APIIPAMVrfsListParams) WithName(name *string) *APIIPAMVrfsListParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the api ipam vrfs list params
func (o *APIIPAMVrfsListParams) SetName(name *string) {
	o.Name = name
}

// WithOffset adds the offset to the api ipam vrfs list params
func (o *APIIPAMVrfsListParams) WithOffset(offset *int64) *APIIPAMVrfsListParams {
	o.SetOffset(offset)
	return o
}

// SetOffset adds the offset to the api ipam vrfs list params
func (o *APIIPAMVrfsListParams) SetOffset(offset *int64) {
	o.Offset = offset
}

// WithQ adds the q to the api ipam vrfs list params
func (o *APIIPAMVrfsListParams) WithQ(q *string) *APIIPAMVrfsListParams {
	o.SetQ(q)
	return o
}

// SetQ adds the q to the api ipam vrfs list params
func (o *APIIPAMVrfsListParams) SetQ(q *string) {
	o.Q = q
}

// WithRd adds the rd to the api ipam vrfs list params
func (o *APIIPAMVrfsListParams) WithRd(rd *string) *APIIPAMVrfsListParams {
	o.SetRd(rd)
	return o
}

// SetRd adds the rd to the api ipam vrfs list params
func (o *APIIPAMVrfsListParams) SetRd(rd *string) {
	o.Rd = rd
}

// WithTag adds the tag to the api ipam vrfs list params
func (o *APIIPAMVrfsListParams) WithTag(tag *string) *APIIPAMVrfsListParams {
	o.SetTag(tag)
	return o
}

// SetTag adds the tag to the api ipam vrfs list params
func (o *APIIPAMVrfsListParams) SetTag(tag *string) {
	o.Tag = tag
}

// WithTenant adds the tenant to the api ipam vrfs list params
func (o *APIIPAMVrfsListParams) WithTenant(tenant *string) *APIIPAMVrfsListParams {
	o.SetTenant(tenant)
	return o
}

// SetTenant adds the tenant to the api ipam vrfs list params
func (o *APIIPAMVrfsListParams) SetTenant(tenant *string) {
	o.Tenant = tenant
}

// WithTenantID adds the tenantID to the api ipam vrfs list params
func (o *APIIPAMVrfsListParams) WithTenantID(tenantID *string) *APIIPAMVrfsListParams {
	o.SetTenantID(tenantID)
	return o
}

// SetTenantID adds the tenantId to the api ipam vrfs list params
func (o *APIIPAMVrfsListParams) SetTenantID(tenantID *string) {
	o.TenantID = tenantID
}

// WriteToRequest writes these params to a swagger request
func (o *APIIPAMVrfsListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.EnforceUnique != nil {

		// query param enforce_unique
		var qrEnforceUnique string
		if o.EnforceUnique != nil {
			qrEnforceUnique = *o.EnforceUnique
		}
		qEnforceUnique := qrEnforceUnique
		if qEnforceUnique != "" {
			if err := r.SetQueryParam("enforce_unique", qEnforceUnique); err != nil {
				return err
			}
		}

	}

	if o.IDIn != nil {

		// query param id__in
		var qrIDIn string
		if o.IDIn != nil {
			qrIDIn = *o.IDIn
		}
		qIDIn := qrIDIn
		if qIDIn != "" {
			if err := r.SetQueryParam("id__in", qIDIn); err != nil {
				return err
			}
		}

	}

	if o.Limit != nil {

		// query param limit
		var qrLimit int64
		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt64(qrLimit)
		if qLimit != "" {
			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}

	}

	if o.Name != nil {

		// query param name
		var qrName string
		if o.Name != nil {
			qrName = *o.Name
		}
		qName := qrName
		if qName != "" {
			if err := r.SetQueryParam("name", qName); err != nil {
				return err
			}
		}

	}

	if o.Offset != nil {

		// query param offset
		var qrOffset int64
		if o.Offset != nil {
			qrOffset = *o.Offset
		}
		qOffset := swag.FormatInt64(qrOffset)
		if qOffset != "" {
			if err := r.SetQueryParam("offset", qOffset); err != nil {
				return err
			}
		}

	}

	if o.Q != nil {

		// query param q
		var qrQ string
		if o.Q != nil {
			qrQ = *o.Q
		}
		qQ := qrQ
		if qQ != "" {
			if err := r.SetQueryParam("q", qQ); err != nil {
				return err
			}
		}

	}

	if o.Rd != nil {

		// query param rd
		var qrRd string
		if o.Rd != nil {
			qrRd = *o.Rd
		}
		qRd := qrRd
		if qRd != "" {
			if err := r.SetQueryParam("rd", qRd); err != nil {
				return err
			}
		}

	}

	if o.Tag != nil {

		// query param tag
		var qrTag string
		if o.Tag != nil {
			qrTag = *o.Tag
		}
		qTag := qrTag
		if qTag != "" {
			if err := r.SetQueryParam("tag", qTag); err != nil {
				return err
			}
		}

	}

	if o.Tenant != nil {

		// query param tenant
		var qrTenant string
		if o.Tenant != nil {
			qrTenant = *o.Tenant
		}
		qTenant := qrTenant
		if qTenant != "" {
			if err := r.SetQueryParam("tenant", qTenant); err != nil {
				return err
			}
		}

	}

	if o.TenantID != nil {

		// query param tenant_id
		var qrTenantID string
		if o.TenantID != nil {
			qrTenantID = *o.TenantID
		}
		qTenantID := qrTenantID
		if qTenantID != "" {
			if err := r.SetQueryParam("tenant_id", qTenantID); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
