// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2018 The go-netbox Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewAPIDcimDeviceBayTemplatesDeleteParams creates a new APIDcimDeviceBayTemplatesDeleteParams object
// with the default values initialized.
func NewAPIDcimDeviceBayTemplatesDeleteParams() *APIDcimDeviceBayTemplatesDeleteParams {
	var ()
	return &APIDcimDeviceBayTemplatesDeleteParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewAPIDcimDeviceBayTemplatesDeleteParamsWithTimeout creates a new APIDcimDeviceBayTemplatesDeleteParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewAPIDcimDeviceBayTemplatesDeleteParamsWithTimeout(timeout time.Duration) *APIDcimDeviceBayTemplatesDeleteParams {
	var ()
	return &APIDcimDeviceBayTemplatesDeleteParams{

		timeout: timeout,
	}
}

// NewAPIDcimDeviceBayTemplatesDeleteParamsWithContext creates a new APIDcimDeviceBayTemplatesDeleteParams object
// with the default values initialized, and the ability to set a context for a request
func NewAPIDcimDeviceBayTemplatesDeleteParamsWithContext(ctx context.Context) *APIDcimDeviceBayTemplatesDeleteParams {
	var ()
	return &APIDcimDeviceBayTemplatesDeleteParams{

		Context: ctx,
	}
}

// NewAPIDcimDeviceBayTemplatesDeleteParamsWithHTTPClient creates a new APIDcimDeviceBayTemplatesDeleteParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewAPIDcimDeviceBayTemplatesDeleteParamsWithHTTPClient(client *http.Client) *APIDcimDeviceBayTemplatesDeleteParams {
	var ()
	return &APIDcimDeviceBayTemplatesDeleteParams{
		HTTPClient: client,
	}
}

/*APIDcimDeviceBayTemplatesDeleteParams contains all the parameters to send to the API endpoint
for the api dcim device bay templates delete operation typically these are written to a http.Request
*/
type APIDcimDeviceBayTemplatesDeleteParams struct {

	/*ID
	  A unique integer value identifying this device bay template.

	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the api dcim device bay templates delete params
func (o *APIDcimDeviceBayTemplatesDeleteParams) WithTimeout(timeout time.Duration) *APIDcimDeviceBayTemplatesDeleteParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the api dcim device bay templates delete params
func (o *APIDcimDeviceBayTemplatesDeleteParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the api dcim device bay templates delete params
func (o *APIDcimDeviceBayTemplatesDeleteParams) WithContext(ctx context.Context) *APIDcimDeviceBayTemplatesDeleteParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the api dcim device bay templates delete params
func (o *APIDcimDeviceBayTemplatesDeleteParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the api dcim device bay templates delete params
func (o *APIDcimDeviceBayTemplatesDeleteParams) WithHTTPClient(client *http.Client) *APIDcimDeviceBayTemplatesDeleteParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the api dcim device bay templates delete params
func (o *APIDcimDeviceBayTemplatesDeleteParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the api dcim device bay templates delete params
func (o *APIDcimDeviceBayTemplatesDeleteParams) WithID(id int64) *APIDcimDeviceBayTemplatesDeleteParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the api dcim device bay templates delete params
func (o *APIDcimDeviceBayTemplatesDeleteParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *APIDcimDeviceBayTemplatesDeleteParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
