// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2018 The go-netbox Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewAPIDcimRackGroupsListParams creates a new APIDcimRackGroupsListParams object
// with the default values initialized.
func NewAPIDcimRackGroupsListParams() *APIDcimRackGroupsListParams {
	var ()
	return &APIDcimRackGroupsListParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewAPIDcimRackGroupsListParamsWithTimeout creates a new APIDcimRackGroupsListParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewAPIDcimRackGroupsListParamsWithTimeout(timeout time.Duration) *APIDcimRackGroupsListParams {
	var ()
	return &APIDcimRackGroupsListParams{

		timeout: timeout,
	}
}

// NewAPIDcimRackGroupsListParamsWithContext creates a new APIDcimRackGroupsListParams object
// with the default values initialized, and the ability to set a context for a request
func NewAPIDcimRackGroupsListParamsWithContext(ctx context.Context) *APIDcimRackGroupsListParams {
	var ()
	return &APIDcimRackGroupsListParams{

		Context: ctx,
	}
}

// NewAPIDcimRackGroupsListParamsWithHTTPClient creates a new APIDcimRackGroupsListParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewAPIDcimRackGroupsListParamsWithHTTPClient(client *http.Client) *APIDcimRackGroupsListParams {
	var ()
	return &APIDcimRackGroupsListParams{
		HTTPClient: client,
	}
}

/*APIDcimRackGroupsListParams contains all the parameters to send to the API endpoint
for the api dcim rack groups list operation typically these are written to a http.Request
*/
type APIDcimRackGroupsListParams struct {

	/*Limit
	  Number of results to return per page.

	*/
	Limit *int64
	/*Name*/
	Name *string
	/*Offset
	  The initial index from which to return the results.

	*/
	Offset *int64
	/*Q*/
	Q *string
	/*Site*/
	Site *string
	/*SiteID*/
	SiteID *string
	/*Slug*/
	Slug *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the api dcim rack groups list params
func (o *APIDcimRackGroupsListParams) WithTimeout(timeout time.Duration) *APIDcimRackGroupsListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the api dcim rack groups list params
func (o *APIDcimRackGroupsListParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the api dcim rack groups list params
func (o *APIDcimRackGroupsListParams) WithContext(ctx context.Context) *APIDcimRackGroupsListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the api dcim rack groups list params
func (o *APIDcimRackGroupsListParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the api dcim rack groups list params
func (o *APIDcimRackGroupsListParams) WithHTTPClient(client *http.Client) *APIDcimRackGroupsListParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the api dcim rack groups list params
func (o *APIDcimRackGroupsListParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithLimit adds the limit to the api dcim rack groups list params
func (o *APIDcimRackGroupsListParams) WithLimit(limit *int64) *APIDcimRackGroupsListParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the api dcim rack groups list params
func (o *APIDcimRackGroupsListParams) SetLimit(limit *int64) {
	o.Limit = limit
}

// WithName adds the name to the api dcim rack groups list params
func (o *APIDcimRackGroupsListParams) WithName(name *string) *APIDcimRackGroupsListParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the api dcim rack groups list params
func (o *APIDcimRackGroupsListParams) SetName(name *string) {
	o.Name = name
}

// WithOffset adds the offset to the api dcim rack groups list params
func (o *APIDcimRackGroupsListParams) WithOffset(offset *int64) *APIDcimRackGroupsListParams {
	o.SetOffset(offset)
	return o
}

// SetOffset adds the offset to the api dcim rack groups list params
func (o *APIDcimRackGroupsListParams) SetOffset(offset *int64) {
	o.Offset = offset
}

// WithQ adds the q to the api dcim rack groups list params
func (o *APIDcimRackGroupsListParams) WithQ(q *string) *APIDcimRackGroupsListParams {
	o.SetQ(q)
	return o
}

// SetQ adds the q to the api dcim rack groups list params
func (o *APIDcimRackGroupsListParams) SetQ(q *string) {
	o.Q = q
}

// WithSite adds the site to the api dcim rack groups list params
func (o *APIDcimRackGroupsListParams) WithSite(site *string) *APIDcimRackGroupsListParams {
	o.SetSite(site)
	return o
}

// SetSite adds the site to the api dcim rack groups list params
func (o *APIDcimRackGroupsListParams) SetSite(site *string) {
	o.Site = site
}

// WithSiteID adds the siteID to the api dcim rack groups list params
func (o *APIDcimRackGroupsListParams) WithSiteID(siteID *string) *APIDcimRackGroupsListParams {
	o.SetSiteID(siteID)
	return o
}

// SetSiteID adds the siteId to the api dcim rack groups list params
func (o *APIDcimRackGroupsListParams) SetSiteID(siteID *string) {
	o.SiteID = siteID
}

// WithSlug adds the slug to the api dcim rack groups list params
func (o *APIDcimRackGroupsListParams) WithSlug(slug *string) *APIDcimRackGroupsListParams {
	o.SetSlug(slug)
	return o
}

// SetSlug adds the slug to the api dcim rack groups list params
func (o *APIDcimRackGroupsListParams) SetSlug(slug *string) {
	o.Slug = slug
}

// WriteToRequest writes these params to a swagger request
func (o *APIDcimRackGroupsListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Limit != nil {

		// query param limit
		var qrLimit int64
		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt64(qrLimit)
		if qLimit != "" {
			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}

	}

	if o.Name != nil {

		// query param name
		var qrName string
		if o.Name != nil {
			qrName = *o.Name
		}
		qName := qrName
		if qName != "" {
			if err := r.SetQueryParam("name", qName); err != nil {
				return err
			}
		}

	}

	if o.Offset != nil {

		// query param offset
		var qrOffset int64
		if o.Offset != nil {
			qrOffset = *o.Offset
		}
		qOffset := swag.FormatInt64(qrOffset)
		if qOffset != "" {
			if err := r.SetQueryParam("offset", qOffset); err != nil {
				return err
			}
		}

	}

	if o.Q != nil {

		// query param q
		var qrQ string
		if o.Q != nil {
			qrQ = *o.Q
		}
		qQ := qrQ
		if qQ != "" {
			if err := r.SetQueryParam("q", qQ); err != nil {
				return err
			}
		}

	}

	if o.Site != nil {

		// query param site
		var qrSite string
		if o.Site != nil {
			qrSite = *o.Site
		}
		qSite := qrSite
		if qSite != "" {
			if err := r.SetQueryParam("site", qSite); err != nil {
				return err
			}
		}

	}

	if o.SiteID != nil {

		// query param site_id
		var qrSiteID string
		if o.SiteID != nil {
			qrSiteID = *o.SiteID
		}
		qSiteID := qrSiteID
		if qSiteID != "" {
			if err := r.SetQueryParam("site_id", qSiteID); err != nil {
				return err
			}
		}

	}

	if o.Slug != nil {

		// query param slug
		var qrSlug string
		if o.Slug != nil {
			qrSlug = *o.Slug
		}
		qSlug := qrSlug
		if qSlug != "" {
			if err := r.SetQueryParam("slug", qSlug); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
