// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2018 The go-netbox Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewAPIIPAMVlansListParams creates a new APIIPAMVlansListParams object
// with the default values initialized.
func NewAPIIPAMVlansListParams() *APIIPAMVlansListParams {
	var ()
	return &APIIPAMVlansListParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewAPIIPAMVlansListParamsWithTimeout creates a new APIIPAMVlansListParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewAPIIPAMVlansListParamsWithTimeout(timeout time.Duration) *APIIPAMVlansListParams {
	var ()
	return &APIIPAMVlansListParams{

		timeout: timeout,
	}
}

// NewAPIIPAMVlansListParamsWithContext creates a new APIIPAMVlansListParams object
// with the default values initialized, and the ability to set a context for a request
func NewAPIIPAMVlansListParamsWithContext(ctx context.Context) *APIIPAMVlansListParams {
	var ()
	return &APIIPAMVlansListParams{

		Context: ctx,
	}
}

// NewAPIIPAMVlansListParamsWithHTTPClient creates a new APIIPAMVlansListParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewAPIIPAMVlansListParamsWithHTTPClient(client *http.Client) *APIIPAMVlansListParams {
	var ()
	return &APIIPAMVlansListParams{
		HTTPClient: client,
	}
}

/*APIIPAMVlansListParams contains all the parameters to send to the API endpoint
for the api ipam vlans list operation typically these are written to a http.Request
*/
type APIIPAMVlansListParams struct {

	/*Group*/
	Group *string
	/*GroupID*/
	GroupID *string
	/*IDIn
	  Multiple values may be separated by commas.

	*/
	IDIn *string
	/*Limit
	  Number of results to return per page.

	*/
	Limit *int64
	/*Name*/
	Name *string
	/*Offset
	  The initial index from which to return the results.

	*/
	Offset *int64
	/*Q*/
	Q *string
	/*Role*/
	Role *string
	/*RoleID*/
	RoleID *string
	/*Site*/
	Site *string
	/*SiteID*/
	SiteID *string
	/*Status*/
	Status *string
	/*Tag*/
	Tag *string
	/*Tenant*/
	Tenant *string
	/*TenantID*/
	TenantID *string
	/*Vid*/
	Vid *float64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the api ipam vlans list params
func (o *APIIPAMVlansListParams) WithTimeout(timeout time.Duration) *APIIPAMVlansListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the api ipam vlans list params
func (o *APIIPAMVlansListParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the api ipam vlans list params
func (o *APIIPAMVlansListParams) WithContext(ctx context.Context) *APIIPAMVlansListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the api ipam vlans list params
func (o *APIIPAMVlansListParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the api ipam vlans list params
func (o *APIIPAMVlansListParams) WithHTTPClient(client *http.Client) *APIIPAMVlansListParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the api ipam vlans list params
func (o *APIIPAMVlansListParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithGroup adds the group to the api ipam vlans list params
func (o *APIIPAMVlansListParams) WithGroup(group *string) *APIIPAMVlansListParams {
	o.SetGroup(group)
	return o
}

// SetGroup adds the group to the api ipam vlans list params
func (o *APIIPAMVlansListParams) SetGroup(group *string) {
	o.Group = group
}

// WithGroupID adds the groupID to the api ipam vlans list params
func (o *APIIPAMVlansListParams) WithGroupID(groupID *string) *APIIPAMVlansListParams {
	o.SetGroupID(groupID)
	return o
}

// SetGroupID adds the groupId to the api ipam vlans list params
func (o *APIIPAMVlansListParams) SetGroupID(groupID *string) {
	o.GroupID = groupID
}

// WithIDIn adds the iDIn to the api ipam vlans list params
func (o *APIIPAMVlansListParams) WithIDIn(iDIn *string) *APIIPAMVlansListParams {
	o.SetIDIn(iDIn)
	return o
}

// SetIDIn adds the idIn to the api ipam vlans list params
func (o *APIIPAMVlansListParams) SetIDIn(iDIn *string) {
	o.IDIn = iDIn
}

// WithLimit adds the limit to the api ipam vlans list params
func (o *APIIPAMVlansListParams) WithLimit(limit *int64) *APIIPAMVlansListParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the api ipam vlans list params
func (o *APIIPAMVlansListParams) SetLimit(limit *int64) {
	o.Limit = limit
}

// WithName adds the name to the api ipam vlans list params
func (o *APIIPAMVlansListParams) WithName(name *string) *APIIPAMVlansListParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the api ipam vlans list params
func (o *APIIPAMVlansListParams) SetName(name *string) {
	o.Name = name
}

// WithOffset adds the offset to the api ipam vlans list params
func (o *APIIPAMVlansListParams) WithOffset(offset *int64) *APIIPAMVlansListParams {
	o.SetOffset(offset)
	return o
}

// SetOffset adds the offset to the api ipam vlans list params
func (o *APIIPAMVlansListParams) SetOffset(offset *int64) {
	o.Offset = offset
}

// WithQ adds the q to the api ipam vlans list params
func (o *APIIPAMVlansListParams) WithQ(q *string) *APIIPAMVlansListParams {
	o.SetQ(q)
	return o
}

// SetQ adds the q to the api ipam vlans list params
func (o *APIIPAMVlansListParams) SetQ(q *string) {
	o.Q = q
}

// WithRole adds the role to the api ipam vlans list params
func (o *APIIPAMVlansListParams) WithRole(role *string) *APIIPAMVlansListParams {
	o.SetRole(role)
	return o
}

// SetRole adds the role to the api ipam vlans list params
func (o *APIIPAMVlansListParams) SetRole(role *string) {
	o.Role = role
}

// WithRoleID adds the roleID to the api ipam vlans list params
func (o *APIIPAMVlansListParams) WithRoleID(roleID *string) *APIIPAMVlansListParams {
	o.SetRoleID(roleID)
	return o
}

// SetRoleID adds the roleId to the api ipam vlans list params
func (o *APIIPAMVlansListParams) SetRoleID(roleID *string) {
	o.RoleID = roleID
}

// WithSite adds the site to the api ipam vlans list params
func (o *APIIPAMVlansListParams) WithSite(site *string) *APIIPAMVlansListParams {
	o.SetSite(site)
	return o
}

// SetSite adds the site to the api ipam vlans list params
func (o *APIIPAMVlansListParams) SetSite(site *string) {
	o.Site = site
}

// WithSiteID adds the siteID to the api ipam vlans list params
func (o *APIIPAMVlansListParams) WithSiteID(siteID *string) *APIIPAMVlansListParams {
	o.SetSiteID(siteID)
	return o
}

// SetSiteID adds the siteId to the api ipam vlans list params
func (o *APIIPAMVlansListParams) SetSiteID(siteID *string) {
	o.SiteID = siteID
}

// WithStatus adds the status to the api ipam vlans list params
func (o *APIIPAMVlansListParams) WithStatus(status *string) *APIIPAMVlansListParams {
	o.SetStatus(status)
	return o
}

// SetStatus adds the status to the api ipam vlans list params
func (o *APIIPAMVlansListParams) SetStatus(status *string) {
	o.Status = status
}

// WithTag adds the tag to the api ipam vlans list params
func (o *APIIPAMVlansListParams) WithTag(tag *string) *APIIPAMVlansListParams {
	o.SetTag(tag)
	return o
}

// SetTag adds the tag to the api ipam vlans list params
func (o *APIIPAMVlansListParams) SetTag(tag *string) {
	o.Tag = tag
}

// WithTenant adds the tenant to the api ipam vlans list params
func (o *APIIPAMVlansListParams) WithTenant(tenant *string) *APIIPAMVlansListParams {
	o.SetTenant(tenant)
	return o
}

// SetTenant adds the tenant to the api ipam vlans list params
func (o *APIIPAMVlansListParams) SetTenant(tenant *string) {
	o.Tenant = tenant
}

// WithTenantID adds the tenantID to the api ipam vlans list params
func (o *APIIPAMVlansListParams) WithTenantID(tenantID *string) *APIIPAMVlansListParams {
	o.SetTenantID(tenantID)
	return o
}

// SetTenantID adds the tenantId to the api ipam vlans list params
func (o *APIIPAMVlansListParams) SetTenantID(tenantID *string) {
	o.TenantID = tenantID
}

// WithVid adds the vid to the api ipam vlans list params
func (o *APIIPAMVlansListParams) WithVid(vid *float64) *APIIPAMVlansListParams {
	o.SetVid(vid)
	return o
}

// SetVid adds the vid to the api ipam vlans list params
func (o *APIIPAMVlansListParams) SetVid(vid *float64) {
	o.Vid = vid
}

// WriteToRequest writes these params to a swagger request
func (o *APIIPAMVlansListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Group != nil {

		// query param group
		var qrGroup string
		if o.Group != nil {
			qrGroup = *o.Group
		}
		qGroup := qrGroup
		if qGroup != "" {
			if err := r.SetQueryParam("group", qGroup); err != nil {
				return err
			}
		}

	}

	if o.GroupID != nil {

		// query param group_id
		var qrGroupID string
		if o.GroupID != nil {
			qrGroupID = *o.GroupID
		}
		qGroupID := qrGroupID
		if qGroupID != "" {
			if err := r.SetQueryParam("group_id", qGroupID); err != nil {
				return err
			}
		}

	}

	if o.IDIn != nil {

		// query param id__in
		var qrIDIn string
		if o.IDIn != nil {
			qrIDIn = *o.IDIn
		}
		qIDIn := qrIDIn
		if qIDIn != "" {
			if err := r.SetQueryParam("id__in", qIDIn); err != nil {
				return err
			}
		}

	}

	if o.Limit != nil {

		// query param limit
		var qrLimit int64
		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt64(qrLimit)
		if qLimit != "" {
			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}

	}

	if o.Name != nil {

		// query param name
		var qrName string
		if o.Name != nil {
			qrName = *o.Name
		}
		qName := qrName
		if qName != "" {
			if err := r.SetQueryParam("name", qName); err != nil {
				return err
			}
		}

	}

	if o.Offset != nil {

		// query param offset
		var qrOffset int64
		if o.Offset != nil {
			qrOffset = *o.Offset
		}
		qOffset := swag.FormatInt64(qrOffset)
		if qOffset != "" {
			if err := r.SetQueryParam("offset", qOffset); err != nil {
				return err
			}
		}

	}

	if o.Q != nil {

		// query param q
		var qrQ string
		if o.Q != nil {
			qrQ = *o.Q
		}
		qQ := qrQ
		if qQ != "" {
			if err := r.SetQueryParam("q", qQ); err != nil {
				return err
			}
		}

	}

	if o.Role != nil {

		// query param role
		var qrRole string
		if o.Role != nil {
			qrRole = *o.Role
		}
		qRole := qrRole
		if qRole != "" {
			if err := r.SetQueryParam("role", qRole); err != nil {
				return err
			}
		}

	}

	if o.RoleID != nil {

		// query param role_id
		var qrRoleID string
		if o.RoleID != nil {
			qrRoleID = *o.RoleID
		}
		qRoleID := qrRoleID
		if qRoleID != "" {
			if err := r.SetQueryParam("role_id", qRoleID); err != nil {
				return err
			}
		}

	}

	if o.Site != nil {

		// query param site
		var qrSite string
		if o.Site != nil {
			qrSite = *o.Site
		}
		qSite := qrSite
		if qSite != "" {
			if err := r.SetQueryParam("site", qSite); err != nil {
				return err
			}
		}

	}

	if o.SiteID != nil {

		// query param site_id
		var qrSiteID string
		if o.SiteID != nil {
			qrSiteID = *o.SiteID
		}
		qSiteID := qrSiteID
		if qSiteID != "" {
			if err := r.SetQueryParam("site_id", qSiteID); err != nil {
				return err
			}
		}

	}

	if o.Status != nil {

		// query param status
		var qrStatus string
		if o.Status != nil {
			qrStatus = *o.Status
		}
		qStatus := qrStatus
		if qStatus != "" {
			if err := r.SetQueryParam("status", qStatus); err != nil {
				return err
			}
		}

	}

	if o.Tag != nil {

		// query param tag
		var qrTag string
		if o.Tag != nil {
			qrTag = *o.Tag
		}
		qTag := qrTag
		if qTag != "" {
			if err := r.SetQueryParam("tag", qTag); err != nil {
				return err
			}
		}

	}

	if o.Tenant != nil {

		// query param tenant
		var qrTenant string
		if o.Tenant != nil {
			qrTenant = *o.Tenant
		}
		qTenant := qrTenant
		if qTenant != "" {
			if err := r.SetQueryParam("tenant", qTenant); err != nil {
				return err
			}
		}

	}

	if o.TenantID != nil {

		// query param tenant_id
		var qrTenantID string
		if o.TenantID != nil {
			qrTenantID = *o.TenantID
		}
		qTenantID := qrTenantID
		if qTenantID != "" {
			if err := r.SetQueryParam("tenant_id", qTenantID); err != nil {
				return err
			}
		}

	}

	if o.Vid != nil {

		// query param vid
		var qrVid float64
		if o.Vid != nil {
			qrVid = *o.Vid
		}
		qVid := swag.FormatFloat64(qrVid)
		if qVid != "" {
			if err := r.SetQueryParam("vid", qVid); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
