// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2018 The go-netbox Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewAPISecretsChoicesReadParams creates a new APISecretsChoicesReadParams object
// with the default values initialized.
func NewAPISecretsChoicesReadParams() *APISecretsChoicesReadParams {
	var ()
	return &APISecretsChoicesReadParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewAPISecretsChoicesReadParamsWithTimeout creates a new APISecretsChoicesReadParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewAPISecretsChoicesReadParamsWithTimeout(timeout time.Duration) *APISecretsChoicesReadParams {
	var ()
	return &APISecretsChoicesReadParams{

		timeout: timeout,
	}
}

// NewAPISecretsChoicesReadParamsWithContext creates a new APISecretsChoicesReadParams object
// with the default values initialized, and the ability to set a context for a request
func NewAPISecretsChoicesReadParamsWithContext(ctx context.Context) *APISecretsChoicesReadParams {
	var ()
	return &APISecretsChoicesReadParams{

		Context: ctx,
	}
}

// NewAPISecretsChoicesReadParamsWithHTTPClient creates a new APISecretsChoicesReadParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewAPISecretsChoicesReadParamsWithHTTPClient(client *http.Client) *APISecretsChoicesReadParams {
	var ()
	return &APISecretsChoicesReadParams{
		HTTPClient: client,
	}
}

/*APISecretsChoicesReadParams contains all the parameters to send to the API endpoint
for the api secrets choices read operation typically these are written to a http.Request
*/
type APISecretsChoicesReadParams struct {

	/*ID*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the api secrets choices read params
func (o *APISecretsChoicesReadParams) WithTimeout(timeout time.Duration) *APISecretsChoicesReadParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the api secrets choices read params
func (o *APISecretsChoicesReadParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the api secrets choices read params
func (o *APISecretsChoicesReadParams) WithContext(ctx context.Context) *APISecretsChoicesReadParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the api secrets choices read params
func (o *APISecretsChoicesReadParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the api secrets choices read params
func (o *APISecretsChoicesReadParams) WithHTTPClient(client *http.Client) *APISecretsChoicesReadParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the api secrets choices read params
func (o *APISecretsChoicesReadParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the api secrets choices read params
func (o *APISecretsChoicesReadParams) WithID(id string) *APISecretsChoicesReadParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the api secrets choices read params
func (o *APISecretsChoicesReadParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *APISecretsChoicesReadParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
