// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2018 The go-netbox Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/digitalocean/go-netbox/netbox/models"
)

// NewAPISecretsSecretRolesCreateParams creates a new APISecretsSecretRolesCreateParams object
// with the default values initialized.
func NewAPISecretsSecretRolesCreateParams() *APISecretsSecretRolesCreateParams {
	var ()
	return &APISecretsSecretRolesCreateParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewAPISecretsSecretRolesCreateParamsWithTimeout creates a new APISecretsSecretRolesCreateParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewAPISecretsSecretRolesCreateParamsWithTimeout(timeout time.Duration) *APISecretsSecretRolesCreateParams {
	var ()
	return &APISecretsSecretRolesCreateParams{

		timeout: timeout,
	}
}

// NewAPISecretsSecretRolesCreateParamsWithContext creates a new APISecretsSecretRolesCreateParams object
// with the default values initialized, and the ability to set a context for a request
func NewAPISecretsSecretRolesCreateParamsWithContext(ctx context.Context) *APISecretsSecretRolesCreateParams {
	var ()
	return &APISecretsSecretRolesCreateParams{

		Context: ctx,
	}
}

// NewAPISecretsSecretRolesCreateParamsWithHTTPClient creates a new APISecretsSecretRolesCreateParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewAPISecretsSecretRolesCreateParamsWithHTTPClient(client *http.Client) *APISecretsSecretRolesCreateParams {
	var ()
	return &APISecretsSecretRolesCreateParams{
		HTTPClient: client,
	}
}

/*APISecretsSecretRolesCreateParams contains all the parameters to send to the API endpoint
for the api secrets secret roles create operation typically these are written to a http.Request
*/
type APISecretsSecretRolesCreateParams struct {

	/*Data*/
	Data *models.SecretRole

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the api secrets secret roles create params
func (o *APISecretsSecretRolesCreateParams) WithTimeout(timeout time.Duration) *APISecretsSecretRolesCreateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the api secrets secret roles create params
func (o *APISecretsSecretRolesCreateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the api secrets secret roles create params
func (o *APISecretsSecretRolesCreateParams) WithContext(ctx context.Context) *APISecretsSecretRolesCreateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the api secrets secret roles create params
func (o *APISecretsSecretRolesCreateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the api secrets secret roles create params
func (o *APISecretsSecretRolesCreateParams) WithHTTPClient(client *http.Client) *APISecretsSecretRolesCreateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the api secrets secret roles create params
func (o *APISecretsSecretRolesCreateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithData adds the data to the api secrets secret roles create params
func (o *APISecretsSecretRolesCreateParams) WithData(data *models.SecretRole) *APISecretsSecretRolesCreateParams {
	o.SetData(data)
	return o
}

// SetData adds the data to the api secrets secret roles create params
func (o *APISecretsSecretRolesCreateParams) SetData(data *models.SecretRole) {
	o.Data = data
}

// WriteToRequest writes these params to a swagger request
func (o *APISecretsSecretRolesCreateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Data != nil {
		if err := r.SetBodyParam(o.Data); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
