// Copyright 2017 The go-netbox Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by generate_functions.go. DO NOT EDIT.

package netbox

import (
	"encoding/json"
	"fmt"
	"net/http"
)

// IPAddressesService is used in a Client to access NetBox's ipam/ip-addresses API methods.
type IPAddressesService struct {
	c *Client
}

// Get retrieves an IPAddress object from NetBox by its ID.
func (s *IPAddressesService) Get(id int) (*IPAddress, error) {
	req, err := s.c.NewRequest(
		http.MethodGet,
		fmt.Sprintf("api/ipam/ip-addresses/%d/", id),
		nil,
	)
	if err != nil {
		return nil, err
	}

	t := new(IPAddress)
	err = s.c.Do(req, t)
	if err != nil {
		return nil, err
	}
	return t, nil
}

// List returns a Page associated with an NetBox API Endpoint.
func (s *IPAddressesService) List(options *ListIPAddressOptions) *Page {
	return NewPage(s.c, "api/ipam/ip-addresses/", options)
}

// Extract retrives a list of IPAddress objects from page.
func (s *IPAddressesService) Extract(page *Page) ([]*IPAddress, error) {
	if err := page.Err(); err != nil {
		return nil, err
	}

	var groups []*IPAddress
	if err := json.Unmarshal(page.data.Results, &groups); err != nil {
		return nil, err
	}
	return groups, nil
}

// Create creates a new IPAddress object in NetBox and returns the ID of the new object.
func (s *IPAddressesService) Create(data *IPAddress) (int, error) {
	req, err := s.c.NewJSONRequest(http.MethodPost, "api/ipam/ip-addresses/", nil, data)
	if err != nil {
		return 0, err
	}

	g := new(writableIPAddress)
	err = s.c.Do(req, g)
	if err != nil {
		return 0, err
	}
	return g.ID, nil
}

// Update changes an existing IPAddress object in NetBox, and returns the ID of the new object.
func (s *IPAddressesService) Update(data *IPAddress) (int, error) {
	req, err := s.c.NewJSONRequest(
		http.MethodPatch,
		fmt.Sprintf("api/ipam/ip-addresses/%d/", data.ID),
		nil,
		data,
	)
	if err != nil {
		return 0, err
	}

	// g is just used to verify correct api result.
	// data is not changed, because the g is not the full representation that one would
	// get with Get. But if the response was unmarshaled into writableIPAddress correctly,
	// everything went fine, and we do not need to update data.
	g := new(writableIPAddress)
	err = s.c.Do(req, g)
	if err != nil {
		return 0, err
	}
	return g.ID, nil
}

// Delete deletes an existing IPAddress object from NetBox.
func (s *IPAddressesService) Delete(data *IPAddress) error {
	req, err := s.c.NewRequest(
		http.MethodDelete,
		fmt.Sprintf("api/ipam/ip-addresses/%d/", data.ID),
		nil,
	)
	if err != nil {
		return err
	}

	return s.c.Do(req, nil)
}
